import {
  BenefitIcon,
  CardIcon,
  ChatIcon,
  ContentIcon,
  DefaultInfoIcon,
  HomeIcon,
  JoinIcon,
  LinkIcon,
  MemberIcon,
  MessageIcon,
  MyInfoIcon,
  OperationIcon,
  PartnerGoogleIcon,
  PartnerKakaoIcon,
  PartnerMetaIcon,
  PartnerNaverIcon,
  PayMethodIcon,
  ProductIcon,
  ReviewIcon,
  ShoppingIcon,
  SiteIcon,
} from '../asset/index'

export const iconMap = {
  홈: <HomeIcon />,
  상품: <ProductIcon />,
  판매: <CardIcon />,
  '쇼핑 연동': <LinkIcon />,
  혜택: <BenefitIcon />,
  리뷰: <ReviewIcon />,
  문의: <ChatIcon />,
  회원: <MemberIcon />,
  메시지: <MessageIcon />,
  콘텐츠: <ContentIcon />,
  기본정보: <DefaultInfoIcon />,
  운영환경: <OperationIcon />,
  회원가입: <JoinIcon />,
  쇼핑환경: <ShoppingIcon />,
  결제수단: <PayMethodIcon />,
  네이버: <PartnerNaverIcon />,
  구글: <PartnerGoogleIcon />,
  메타: <PartnerMetaIcon />,
  카카오: <PartnerKakaoIcon />,
  '사이트 바로가기': <SiteIcon />,
  '내 정보': <MyInfoIcon />,
}
